

[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/validate"
  version = "0.16.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  version = "1.4.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.5.0"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true
