// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "XWORD",
    "title": "xword",
    "contact": {
      "email": "phil.shebel@gmail.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/user": {
      "put": {
        "description": "Creates a cookie for user and gets user data",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "name identifying the user",
            "name": "username",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Put user successful response",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "description": "Gets top 5 users by number of puzzles done or number of words",
        "tags": [
          "users"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "determines whether we get puzzle or word score",
            "name": "value",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Users"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/word": {
      "post": {
        "security": [
          {
            "user": []
          }
        ],
        "description": "Adds word to mongodb",
        "tags": [
          "word"
        ],
        "parameters": [
          {
            "description": "New word and definition",
            "name": "word",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Word"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Post word successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/words": {
      "get": {
        "description": "Get words from db",
        "tags": [
          "words"
        ],
        "parameters": [
          {
            "type": "integer",
            "description": "returns words of a certain length",
            "name": "length",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Words"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/xword": {
      "get": {
        "description": "Get xword from app",
        "tags": [
          "xword"
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Xword"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      },
      "post": {
        "description": "Adds xword to mongodb",
        "tags": [
          "xword"
        ],
        "parameters": [
          {
            "description": "list of words and definitions in puzzle",
            "name": "xword",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Xword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Post xword successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/xword/solve/puzzle": {
      "put": {
        "security": [
          {
            "user": []
          }
        ],
        "description": "Checks if user has solved the xword and updates there count",
        "tags": [
          "xword_solve"
        ],
        "parameters": [
          {
            "description": "puzzle definition",
            "name": "xword",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CheckXword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Check xword successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CheckWord": {
      "type": "object",
      "required": [
        "word_id",
        "input",
        "idx",
        "dir"
      ],
      "properties": {
        "dir": {
          "type": "integer"
        },
        "idx": {
          "type": "integer"
        },
        "input": {
          "type": "string"
        },
        "word_id": {
          "type": "integer"
        }
      }
    },
    "CheckXword": {
      "type": "object",
      "properties": {
        "words": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CheckWord"
          }
        },
        "xword_id": {
          "type": "integer"
        }
      }
    },
    "ReturnCode": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "readOnly": true
        },
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "username"
      ],
      "properties": {
        "puzzles": {
          "type": "integer"
        },
        "username": {
          "type": "string"
        },
        "words": {
          "type": "integer"
        }
      }
    },
    "Users": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/User"
      }
    },
    "Word": {
      "type": "object",
      "required": [
        "word",
        "definition"
      ],
      "properties": {
        "definition": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "word": {
          "type": "string"
        },
        "wordLength": {
          "type": "integer"
        }
      }
    },
    "Words": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Word"
      }
    },
    "Xword": {
      "type": "object",
      "required": [
        "words",
        "size"
      ],
      "properties": {
        "id": {
          "type": "integer"
        },
        "size": {
          "type": "integer"
        },
        "words": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/XwordWord"
          }
        }
      }
    },
    "XwordWord": {
      "type": "object",
      "required": [
        "word_id",
        "idx",
        "dir"
      ],
      "properties": {
        "definition": {
          "type": "string"
        },
        "dir": {
          "type": "integer"
        },
        "idx": {
          "type": "integer"
        },
        "word_id": {
          "type": "integer"
        },
        "word_len": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "user": {
      "type": "apiKey",
      "name": "user",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "XWORD",
    "title": "xword",
    "contact": {
      "email": "phil.shebel@gmail.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/user": {
      "put": {
        "description": "Creates a cookie for user and gets user data",
        "tags": [
          "user"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "name identifying the user",
            "name": "username",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Put user successful response",
            "schema": {
              "$ref": "#/definitions/User"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "description": "Gets top 5 users by number of puzzles done or number of words",
        "tags": [
          "users"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "determines whether we get puzzle or word score",
            "name": "value",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Users"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/word": {
      "post": {
        "security": [
          {
            "user": []
          }
        ],
        "description": "Adds word to mongodb",
        "tags": [
          "word"
        ],
        "parameters": [
          {
            "description": "New word and definition",
            "name": "word",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Word"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Post word successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/words": {
      "get": {
        "description": "Get words from db",
        "tags": [
          "words"
        ],
        "parameters": [
          {
            "type": "integer",
            "description": "returns words of a certain length",
            "name": "length",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Words"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/xword": {
      "get": {
        "description": "Get xword from app",
        "tags": [
          "xword"
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Xword"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      },
      "post": {
        "description": "Adds xword to mongodb",
        "tags": [
          "xword"
        ],
        "parameters": [
          {
            "description": "list of words and definitions in puzzle",
            "name": "xword",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Xword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Post xword successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/xword/solve/puzzle": {
      "put": {
        "security": [
          {
            "user": []
          }
        ],
        "description": "Checks if user has solved the xword and updates there count",
        "tags": [
          "xword_solve"
        ],
        "parameters": [
          {
            "description": "puzzle definition",
            "name": "xword",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CheckXword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Check xword successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CheckWord": {
      "type": "object",
      "required": [
        "word_id",
        "input",
        "idx",
        "dir"
      ],
      "properties": {
        "dir": {
          "type": "integer"
        },
        "idx": {
          "type": "integer"
        },
        "input": {
          "type": "string"
        },
        "word_id": {
          "type": "integer"
        }
      }
    },
    "CheckXword": {
      "type": "object",
      "properties": {
        "words": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CheckWord"
          }
        },
        "xword_id": {
          "type": "integer"
        }
      }
    },
    "ReturnCode": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "readOnly": true
        },
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "User": {
      "type": "object",
      "required": [
        "username"
      ],
      "properties": {
        "puzzles": {
          "type": "integer"
        },
        "username": {
          "type": "string"
        },
        "words": {
          "type": "integer"
        }
      }
    },
    "Users": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/User"
      }
    },
    "Word": {
      "type": "object",
      "required": [
        "word",
        "definition"
      ],
      "properties": {
        "definition": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "word": {
          "type": "string"
        },
        "wordLength": {
          "type": "integer"
        }
      }
    },
    "Words": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Word"
      }
    },
    "Xword": {
      "type": "object",
      "required": [
        "words",
        "size"
      ],
      "properties": {
        "id": {
          "type": "integer"
        },
        "size": {
          "type": "integer"
        },
        "words": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/XwordWord"
          }
        }
      }
    },
    "XwordWord": {
      "type": "object",
      "required": [
        "word_id",
        "idx",
        "dir"
      ],
      "properties": {
        "definition": {
          "type": "string"
        },
        "dir": {
          "type": "integer"
        },
        "idx": {
          "type": "integer"
        },
        "word_id": {
          "type": "integer"
        },
        "word_len": {
          "type": "integer"
        }
      }
    }
  },
  "securityDefinitions": {
    "user": {
      "type": "apiKey",
      "name": "user",
      "in": "header"
    }
  }
}`))
}
