// Code generated by go-swagger; DO NOT EDIT.

package words

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pshebel/xword/api/models"
)

// GetWordsOKCode is the HTTP code returned for type GetWordsOK
const GetWordsOKCode int = 200

/*GetWordsOK Successful

swagger:response getWordsOK
*/
type GetWordsOK struct {

	/*
	  In: Body
	*/
	Payload models.Words `json:"body,omitempty"`
}

// NewGetWordsOK creates GetWordsOK with default headers values
func NewGetWordsOK() *GetWordsOK {

	return &GetWordsOK{}
}

// WithPayload adds the payload to the get words o k response
func (o *GetWordsOK) WithPayload(payload models.Words) *GetWordsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get words o k response
func (o *GetWordsOK) SetPayload(payload models.Words) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Words{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetWordsInternalServerErrorCode is the HTTP code returned for type GetWordsInternalServerError
const GetWordsInternalServerErrorCode int = 500

/*GetWordsInternalServerError Internal Server Error

swagger:response getWordsInternalServerError
*/
type GetWordsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetWordsInternalServerError creates GetWordsInternalServerError with default headers values
func NewGetWordsInternalServerError() *GetWordsInternalServerError {

	return &GetWordsInternalServerError{}
}

// WithPayload adds the payload to the get words internal server error response
func (o *GetWordsInternalServerError) WithPayload(payload *models.ReturnCode) *GetWordsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get words internal server error response
func (o *GetWordsInternalServerError) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetWordsDefault Unexpected recovery response

swagger:response getWordsDefault
*/
type GetWordsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetWordsDefault creates GetWordsDefault with default headers values
func NewGetWordsDefault(code int) *GetWordsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetWordsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get words default response
func (o *GetWordsDefault) WithStatusCode(code int) *GetWordsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get words default response
func (o *GetWordsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get words default response
func (o *GetWordsDefault) WithPayload(payload *models.ReturnCode) *GetWordsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get words default response
func (o *GetWordsDefault) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
