// Code generated by go-swagger; DO NOT EDIT.

package word

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostWordHandlerFunc turns a function with the right signature into a post word handler
type PostWordHandlerFunc func(PostWordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostWordHandlerFunc) Handle(params PostWordParams) middleware.Responder {
	return fn(params)
}

// PostWordHandler interface for that can handle valid post word params
type PostWordHandler interface {
	Handle(PostWordParams) middleware.Responder
}

// NewPostWord creates a new http.Handler for the post word operation
func NewPostWord(ctx *middleware.Context, handler PostWordHandler) *PostWord {
	return &PostWord{Context: ctx, Handler: handler}
}

/*PostWord swagger:route POST /word word postWord

Adds word to mongodb

*/
type PostWord struct {
	Context *middleware.Context
	Handler PostWordHandler
}

func (o *PostWord) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostWordParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
