// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi api
XWORD DB


    Schemes:
      http
    Host: localhost
    BasePath: /api
    Version: 0.0.1
    Contact: <phil.shebel@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
