// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "XWORD DB",
    "title": "api",
    "contact": {
      "email": "phil.shebel@gmail.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/word": {
      "get": {
        "description": "Get words from mongodb",
        "tags": [
          "word"
        ],
        "parameters": [
          {
            "type": "integer",
            "description": "returns words of a certain length",
            "name": "length",
            "in": "query"
          },
          {
            "type": "string",
            "description": "returns words that start with a certain prefix",
            "name": "prefix",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Words"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      },
      "post": {
        "description": "Adds word to mongodb",
        "tags": [
          "word"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Username",
            "name": "user",
            "in": "query"
          },
          {
            "description": "New word and definition",
            "name": "word",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Word"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Post word successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "409": {
            "description": "Post word duplicate response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/xword": {
      "get": {
        "description": "Get xword from app",
        "tags": [
          "xword"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Username",
            "name": "user",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Xword"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      },
      "post": {
        "description": "Adds xword to mongodb",
        "tags": [
          "xword"
        ],
        "parameters": [
          {
            "description": "list of words and definitions in puzzle",
            "name": "xword",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Xword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Post xword successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "409": {
            "description": "Post word duplicate response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ReturnCode": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "readOnly": true
        },
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Word": {
      "type": "object",
      "required": [
        "word",
        "definition"
      ],
      "properties": {
        "definition": {
          "type": "string"
        },
        "word": {
          "type": "string"
        }
      }
    },
    "Words": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Word"
      }
    },
    "Xword": {
      "type": "object",
      "required": [
        "words",
        "definitions"
      ],
      "properties": {
        "definitions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "words": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "XWORD DB",
    "title": "api",
    "contact": {
      "email": "phil.shebel@gmail.com"
    },
    "version": "0.0.1"
  },
  "basePath": "/api",
  "paths": {
    "/word": {
      "get": {
        "description": "Get words from mongodb",
        "tags": [
          "word"
        ],
        "parameters": [
          {
            "type": "integer",
            "description": "returns words of a certain length",
            "name": "length",
            "in": "query"
          },
          {
            "type": "string",
            "description": "returns words that start with a certain prefix",
            "name": "prefix",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Words"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      },
      "post": {
        "description": "Adds word to mongodb",
        "tags": [
          "word"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Username",
            "name": "user",
            "in": "query"
          },
          {
            "description": "New word and definition",
            "name": "word",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Word"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Post word successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "409": {
            "description": "Post word duplicate response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    },
    "/xword": {
      "get": {
        "description": "Get xword from app",
        "tags": [
          "xword"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "Username",
            "name": "user",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful",
            "schema": {
              "$ref": "#/definitions/Xword"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Unexpected recovery response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      },
      "post": {
        "description": "Adds xword to mongodb",
        "tags": [
          "xword"
        ],
        "parameters": [
          {
            "description": "list of words and definitions in puzzle",
            "name": "xword",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Xword"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Post xword successful response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "409": {
            "description": "Post word duplicate response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          },
          "default": {
            "description": "Post word unexpected error response",
            "schema": {
              "$ref": "#/definitions/ReturnCode"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ReturnCode": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "readOnly": true
        },
        "message": {
          "type": "string",
          "readOnly": true
        }
      }
    },
    "Word": {
      "type": "object",
      "required": [
        "word",
        "definition"
      ],
      "properties": {
        "definition": {
          "type": "string"
        },
        "word": {
          "type": "string"
        }
      }
    },
    "Words": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Word"
      }
    },
    "Xword": {
      "type": "object",
      "required": [
        "words",
        "definitions"
      ],
      "properties": {
        "definitions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "type": "string"
        },
        "words": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}`))
}
