// Code generated by go-swagger; DO NOT EDIT.

package word

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pshebel/xword/be/models"
)

// GetWordOKCode is the HTTP code returned for type GetWordOK
const GetWordOKCode int = 200

/*GetWordOK Successful

swagger:response getWordOK
*/
type GetWordOK struct {

	/*
	  In: Body
	*/
	Payload models.Words `json:"body,omitempty"`
}

// NewGetWordOK creates GetWordOK with default headers values
func NewGetWordOK() *GetWordOK {

	return &GetWordOK{}
}

// WithPayload adds the payload to the get word o k response
func (o *GetWordOK) WithPayload(payload models.Words) *GetWordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get word o k response
func (o *GetWordOK) SetPayload(payload models.Words) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.Words, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// GetWordNotFoundCode is the HTTP code returned for type GetWordNotFound
const GetWordNotFoundCode int = 404

/*GetWordNotFound Not Found

swagger:response getWordNotFound
*/
type GetWordNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetWordNotFound creates GetWordNotFound with default headers values
func NewGetWordNotFound() *GetWordNotFound {

	return &GetWordNotFound{}
}

// WithPayload adds the payload to the get word not found response
func (o *GetWordNotFound) WithPayload(payload *models.ReturnCode) *GetWordNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get word not found response
func (o *GetWordNotFound) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetWordDefault Unexpected recovery response

swagger:response getWordDefault
*/
type GetWordDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetWordDefault creates GetWordDefault with default headers values
func NewGetWordDefault(code int) *GetWordDefault {
	if code <= 0 {
		code = 500
	}

	return &GetWordDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get word default response
func (o *GetWordDefault) WithStatusCode(code int) *GetWordDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get word default response
func (o *GetWordDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get word default response
func (o *GetWordDefault) WithPayload(payload *models.ReturnCode) *GetWordDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get word default response
func (o *GetWordDefault) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWordDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
