version: '3.7'

services:
  xword-api:
    image: xword-api:latest
    container_name: xword-api
    build:
      context: ../../
      dockerfile: ./api/docker/Dockerfile
    environment: 
      - MARIA_HOST
      - MARIA_USER
      - MARIA_PW
      - MARIA_DB
    ports:
      - '7000:7000'