version: '3.7'

services:
  xword-ui:
    image: xword-ui:latest
    container_name: xword-ui
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production