// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/pshebel/xword/be/models"
)

// PutUserOKCode is the HTTP code returned for type PutUserOK
const PutUserOKCode int = 200

/*PutUserOK Put user successful response

swagger:response putUserOK
*/
type PutUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserOK creates PutUserOK with default headers values
func NewPutUserOK() *PutUserOK {

	return &PutUserOK{}
}

// WithPayload adds the payload to the put user o k response
func (o *PutUserOK) WithPayload(payload *models.ReturnCode) *PutUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user o k response
func (o *PutUserOK) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutUserBadRequestCode is the HTTP code returned for type PutUserBadRequest
const PutUserBadRequestCode int = 400

/*PutUserBadRequest Bad Request

swagger:response putUserBadRequest
*/
type PutUserBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserBadRequest creates PutUserBadRequest with default headers values
func NewPutUserBadRequest() *PutUserBadRequest {

	return &PutUserBadRequest{}
}

// WithPayload adds the payload to the put user bad request response
func (o *PutUserBadRequest) WithPayload(payload *models.ReturnCode) *PutUserBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user bad request response
func (o *PutUserBadRequest) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutUserUnauthorizedCode is the HTTP code returned for type PutUserUnauthorized
const PutUserUnauthorizedCode int = 401

/*PutUserUnauthorized Unauthorized

swagger:response putUserUnauthorized
*/
type PutUserUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserUnauthorized creates PutUserUnauthorized with default headers values
func NewPutUserUnauthorized() *PutUserUnauthorized {

	return &PutUserUnauthorized{}
}

// WithPayload adds the payload to the put user unauthorized response
func (o *PutUserUnauthorized) WithPayload(payload *models.ReturnCode) *PutUserUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user unauthorized response
func (o *PutUserUnauthorized) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutUserNotFoundCode is the HTTP code returned for type PutUserNotFound
const PutUserNotFoundCode int = 404

/*PutUserNotFound Not Found

swagger:response putUserNotFound
*/
type PutUserNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserNotFound creates PutUserNotFound with default headers values
func NewPutUserNotFound() *PutUserNotFound {

	return &PutUserNotFound{}
}

// WithPayload adds the payload to the put user not found response
func (o *PutUserNotFound) WithPayload(payload *models.ReturnCode) *PutUserNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user not found response
func (o *PutUserNotFound) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutUserConflictCode is the HTTP code returned for type PutUserConflict
const PutUserConflictCode int = 409

/*PutUserConflict Post word duplicate response

swagger:response putUserConflict
*/
type PutUserConflict struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserConflict creates PutUserConflict with default headers values
func NewPutUserConflict() *PutUserConflict {

	return &PutUserConflict{}
}

// WithPayload adds the payload to the put user conflict response
func (o *PutUserConflict) WithPayload(payload *models.ReturnCode) *PutUserConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user conflict response
func (o *PutUserConflict) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutUserInternalServerErrorCode is the HTTP code returned for type PutUserInternalServerError
const PutUserInternalServerErrorCode int = 500

/*PutUserInternalServerError Internal Server Error

swagger:response putUserInternalServerError
*/
type PutUserInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserInternalServerError creates PutUserInternalServerError with default headers values
func NewPutUserInternalServerError() *PutUserInternalServerError {

	return &PutUserInternalServerError{}
}

// WithPayload adds the payload to the put user internal server error response
func (o *PutUserInternalServerError) WithPayload(payload *models.ReturnCode) *PutUserInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user internal server error response
func (o *PutUserInternalServerError) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutUserDefault Post word unexpected error response

swagger:response putUserDefault
*/
type PutUserDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserDefault creates PutUserDefault with default headers values
func NewPutUserDefault(code int) *PutUserDefault {
	if code <= 0 {
		code = 500
	}

	return &PutUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put user default response
func (o *PutUserDefault) WithStatusCode(code int) *PutUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put user default response
func (o *PutUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put user default response
func (o *PutUserDefault) WithPayload(payload *models.ReturnCode) *PutUserDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user default response
func (o *PutUserDefault) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
