// LOGIN
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const CHECK_LOGIN_SUCCESS = 'CHECK_LOGIN_SUCCESS';
export const CHECK_LOGIN_FAILURE = 'CHECK_LOGIN_FAILURE';
export const LOGIN_FORM_CHANGE = 'LOGIN_FORM_CHANGE';
// XWORD
export const GET_XWORD = 'GET_XWORD';
export const GET_XWORD_SUCCESS = 'GET_XWORD_SUCCESS';
export const GET_XWORD_FAILURE = 'GET_XWORD_FAILURE';
export const GET_CHECK_XWORD = 'GET_CHECK_XWORD';
export const GET_CHECK_XWORD_SUCCESS = 'GET_CHECK_XWORD_SUCCESS';
export const GET_CHECK_XWORD_FAILURE = 'GET_CHECK_XWORD_FAILURE';
export const XWORD_ELEMENT_CHANGE = 'XWORD_ELEMENT_CHANGE';
export const XWORD_INDEX_CHANGE = 'XWORD_INDEX_CHANGE';
export const XWORD_DIRECTION_CHANGE = 'XWORD_DIRECTION_CHANGE';
// WORDS
export const POST_WORD = 'POST_WORD';
export const POST_WORD_SUCCESS = 'POST_WORD_SUCCESS';
export const POST_WORD_FAILURE = 'POST_WORD_FAILURE';
export const CHANGE_WORD = 'CHANGE_WORD';
export const RESET_WORD = 'RESET_WORD';
// USERS
export const GET_USERS = 'GET_USER';
export const GET_USERS_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USER_FAILURE';


export default {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  CHECK_LOGIN,
  CHECK_LOGIN_SUCCESS,
  CHECK_LOGIN_FAILURE,
  LOGIN_FORM_CHANGE,
  GET_XWORD_SUCCESS,
  GET_XWORD_FAILURE,
  GET_CHECK_XWORD,
  GET_CHECK_XWORD_SUCCESS,
  GET_CHECK_XWORD_FAILURE,
  XWORD_ELEMENT_CHANGE,
  XWORD_INDEX_CHANGE,
  XWORD_DIRECTION_CHANGE,
  POST_WORD,
  POST_WORD_SUCCESS,
  POST_WORD_FAILURE,
  CHANGE_WORD,
  RESET_WORD,
  GET_USERS,
  GET_USERS_SUCCESS,
  GET_USERS_FAILURE,
};