DROP TABLE IF EXISTS padded_words;

DROP TABLE IF EXISTS clues;

DROP TABLE IF EXISTS puzzle_words;

DROP TABLE IF EXISTS words;

DROP TABLE IF EXISTS prompts;

DROP TABLE IF EXISTS puzzles;
