// Code generated by go-swagger; DO NOT EDIT.

package xword

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetXwordParams creates a new GetXwordParams object
// no default values defined in spec.
func NewGetXwordParams() GetXwordParams {

	return GetXwordParams{}
}

// GetXwordParams contains all the bound params for the get xword operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetXword
type GetXwordParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Username
	  In: query
	*/
	User *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetXwordParams() beforehand.
func (o *GetXwordParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qUser, qhkUser, _ := qs.GetOK("user")
	if err := o.bindUser(qUser, qhkUser, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindUser binds and validates parameter User from query.
func (o *GetXwordParams) bindUser(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.User = &raw

	return nil
}
