// Code generated by go-swagger; DO NOT EDIT.

package xword

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pshebel/xword/api/models"
)

// GetXwordOKCode is the HTTP code returned for type GetXwordOK
const GetXwordOKCode int = 200

/*GetXwordOK Successful

swagger:response getXwordOK
*/
type GetXwordOK struct {

	/*
	  In: Body
	*/
	Payload *models.Xword `json:"body,omitempty"`
}

// NewGetXwordOK creates GetXwordOK with default headers values
func NewGetXwordOK() *GetXwordOK {

	return &GetXwordOK{}
}

// WithPayload adds the payload to the get xword o k response
func (o *GetXwordOK) WithPayload(payload *models.Xword) *GetXwordOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get xword o k response
func (o *GetXwordOK) SetPayload(payload *models.Xword) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetXwordOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetXwordInternalServerErrorCode is the HTTP code returned for type GetXwordInternalServerError
const GetXwordInternalServerErrorCode int = 500

/*GetXwordInternalServerError Internal Server Error

swagger:response getXwordInternalServerError
*/
type GetXwordInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetXwordInternalServerError creates GetXwordInternalServerError with default headers values
func NewGetXwordInternalServerError() *GetXwordInternalServerError {

	return &GetXwordInternalServerError{}
}

// WithPayload adds the payload to the get xword internal server error response
func (o *GetXwordInternalServerError) WithPayload(payload *models.ReturnCode) *GetXwordInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get xword internal server error response
func (o *GetXwordInternalServerError) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetXwordInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetXwordDefault Unexpected recovery response

swagger:response getXwordDefault
*/
type GetXwordDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewGetXwordDefault creates GetXwordDefault with default headers values
func NewGetXwordDefault(code int) *GetXwordDefault {
	if code <= 0 {
		code = 500
	}

	return &GetXwordDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get xword default response
func (o *GetXwordDefault) WithStatusCode(code int) *GetXwordDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get xword default response
func (o *GetXwordDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get xword default response
func (o *GetXwordDefault) WithPayload(payload *models.ReturnCode) *GetXwordDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get xword default response
func (o *GetXwordDefault) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetXwordDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
