// Code generated by go-swagger; DO NOT EDIT.

package xword

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostXwordHandlerFunc turns a function with the right signature into a post xword handler
type PostXwordHandlerFunc func(PostXwordParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostXwordHandlerFunc) Handle(params PostXwordParams) middleware.Responder {
	return fn(params)
}

// PostXwordHandler interface for that can handle valid post xword params
type PostXwordHandler interface {
	Handle(PostXwordParams) middleware.Responder
}

// NewPostXword creates a new http.Handler for the post xword operation
func NewPostXword(ctx *middleware.Context, handler PostXwordHandler) *PostXword {
	return &PostXword{Context: ctx, Handler: handler}
}

/*PostXword swagger:route POST /xword xword postXword

Adds xword to mongodb

*/
type PostXword struct {
	Context *middleware.Context
	Handler PostXwordHandler
}

func (o *PostXword) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostXwordParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
