name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
    
    - name: Copy files to server
      run: |
        rsync -avz --delete \
          --exclude '.git' \
          --exclude 'node_modules' \
          --exclude '.env' \
          ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }}:${{ secrets.DEPLOY_PATH }}
    
    - name: Restart nginx
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} \
          "sudo systemctl restart nginx"
    
    - name: Verify deployment
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_HOST }} \
          "sudo systemctl status nginx --no-pager -l"