// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ReturnCode return code
//
// swagger:model ReturnCode
type ReturnCode struct {

	// code
	// Read Only: true
	Code int64 `json:"code,omitempty"`

	// message
	// Read Only: true
	Message string `json:"message,omitempty"`
}

// Validate validates this return code
func (m *ReturnCode) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ReturnCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ReturnCode) UnmarshalBinary(b []byte) error {
	var res ReturnCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
