// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WordCheck word check
// swagger:model WordCheck
type WordCheck struct {

	// input
	// Required: true
	Input *string `json:"input"`

	// word id
	// Required: true
	WordID *int64 `json:"word_id"`
}

// Validate validates this word check
func (m *WordCheck) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInput(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWordID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WordCheck) validateInput(formats strfmt.Registry) error {

	if err := validate.Required("input", "body", m.Input); err != nil {
		return err
	}

	return nil
}

func (m *WordCheck) validateWordID(formats strfmt.Registry) error {

	if err := validate.Required("word_id", "body", m.WordID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WordCheck) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WordCheck) UnmarshalBinary(b []byte) error {
	var res WordCheck
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
