// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Word word
// swagger:model Word
type Word struct {

	// definition
	// Required: true
	Definition *string `json:"definition"`

	// word
	// Required: true
	Word *string `json:"word"`
}

// Validate validates this word
func (m *Word) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefinition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWord(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Word) validateDefinition(formats strfmt.Registry) error {

	if err := validate.Required("definition", "body", m.Definition); err != nil {
		return err
	}

	return nil
}

func (m *Word) validateWord(formats strfmt.Registry) error {

	if err := validate.Required("word", "body", m.Word); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Word) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Word) UnmarshalBinary(b []byte) error {
	var res Word
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
