// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Xword xword
// swagger:model Xword
type Xword struct {

	// definitions
	// Required: true
	Definitions []string `json:"definitions"`

	// id
	ID string `json:"id,omitempty"`

	// words
	// Required: true
	Words []string `json:"words"`
}

// Validate validates this xword
func (m *Xword) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefinitions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWords(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Xword) validateDefinitions(formats strfmt.Registry) error {

	if err := validate.Required("definitions", "body", m.Definitions); err != nil {
		return err
	}

	return nil
}

func (m *Xword) validateWords(formats strfmt.Registry) error {

	if err := validate.Required("words", "body", m.Words); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Xword) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Xword) UnmarshalBinary(b []byte) error {
	var res Xword
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
