// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Xword xword
//
// swagger:model Xword
type Xword struct {

	// id
	ID int64 `json:"id,omitempty"`

	// size
	// Required: true
	Size *int64 `json:"size"`

	// words
	// Required: true
	Words []*XwordWord `json:"words"`
}

// Validate validates this xword
func (m *Xword) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWords(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Xword) validateSize(formats strfmt.Registry) error {

	if err := validate.Required("size", "body", m.Size); err != nil {
		return err
	}

	return nil
}

func (m *Xword) validateWords(formats strfmt.Registry) error {

	if err := validate.Required("words", "body", m.Words); err != nil {
		return err
	}

	for i := 0; i < len(m.Words); i++ {
		if swag.IsZero(m.Words[i]) { // not required
			continue
		}

		if m.Words[i] != nil {
			if err := m.Words[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("words" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Xword) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Xword) UnmarshalBinary(b []byte) error {
	var res Xword
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
