// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pshebel/xword/api/models"
)

// PutUserOKCode is the HTTP code returned for type PutUserOK
const PutUserOKCode int = 200

/*PutUserOK Put user successful response

swagger:response putUserOK
*/
type PutUserOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPutUserOK creates PutUserOK with default headers values
func NewPutUserOK() *PutUserOK {

	return &PutUserOK{}
}

// WithPayload adds the payload to the put user o k response
func (o *PutUserOK) WithPayload(payload *models.User) *PutUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user o k response
func (o *PutUserOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutUserInternalServerErrorCode is the HTTP code returned for type PutUserInternalServerError
const PutUserInternalServerErrorCode int = 500

/*PutUserInternalServerError Internal Server Error

swagger:response putUserInternalServerError
*/
type PutUserInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserInternalServerError creates PutUserInternalServerError with default headers values
func NewPutUserInternalServerError() *PutUserInternalServerError {

	return &PutUserInternalServerError{}
}

// WithPayload adds the payload to the put user internal server error response
func (o *PutUserInternalServerError) WithPayload(payload *models.ReturnCode) *PutUserInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user internal server error response
func (o *PutUserInternalServerError) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutUserDefault Post word unexpected error response

swagger:response putUserDefault
*/
type PutUserDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.ReturnCode `json:"body,omitempty"`
}

// NewPutUserDefault creates PutUserDefault with default headers values
func NewPutUserDefault(code int) *PutUserDefault {
	if code <= 0 {
		code = 500
	}

	return &PutUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put user default response
func (o *PutUserDefault) WithStatusCode(code int) *PutUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put user default response
func (o *PutUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put user default response
func (o *PutUserDefault) WithPayload(payload *models.ReturnCode) *PutUserDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put user default response
func (o *PutUserDefault) SetPayload(payload *models.ReturnCode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
