pipeline {
  agent any

  stages {
    stage('Log') {
        steps {
            sh 'ls -a'
            sh 'printenv'
        }
    }
    
    stage('Build') {
        steps {
            sh 'docker system prune -f'
            sh 'docker-compose -f docker-compose.production.yml build'
        }
    }

    stage('Push') {
        steps {
            sh 'docker tag xword-ui:latest 432883629663.dkr.ecr.us-east-1.amazonaws.com/xword-ui:latest'
            sh '$(aws ecr get-login --no-include-email --region us-east-1)'
            sh 'docker push 432883629663.dkr.ecr.us-east-1.amazonaws.com/xword-ui:latest'
        }
    }
  }
}