swagger: '2.0'
info:
  title: api
  version: 0.0.1
  description: XWORD
  contact:
    email: phil.shebel@gmail.com
basePath: /api
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http

securityDefinitions:
   user:
     type: apiKey
     in: header
     name: user

paths:
  /word:
    post:
      tags:
        - word
      security:
         - user: []
      description: Adds word to mongodb
      parameters:
        - in: body
          name: word
          description: New word and definition
          required: true
          schema:
            $ref: '#/definitions/Word'
      responses:
        '200':
          description: Post word successful response
          schema:
            $ref: '#/definitions/ReturnCode'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ReturnCode'
        default:
          description: Post word unexpected error response
          schema:
            $ref: '#/definitions/ReturnCode'
  /words:
    get:
      tags:
        - words
      description: Get words from db
      parameters:
        - in: query
          name: length
          type: integer
          description: returns words of a certain length
      responses:
        '200':
          description: Successful
          schema:
            $ref: '#/definitions/Words'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ReturnCode'
        default:
          description: Unexpected recovery response
          schema:
            $ref: '#/definitions/ReturnCode'
  /user:
    put:
      tags:
        - user
      description: Creates a cookie for user and gets user data
      parameters:
        - in: query
          name: username
          description: name identifying the user
          required: true
          type: string
      responses:
        '200':
          description: Put user successful response
          schema:
            $ref: '#/definitions/User'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ReturnCode'
        default:
          description: Post word unexpected error response
          schema:
            $ref: '#/definitions/ReturnCode'
  /users:
    get:
      tags:
        - users
      description: Gets top 5 users by number of puzzles done or number of words
      parameters:
        - in: query
          name: value
          type: string
          description: determines whether we get puzzle or word score
      responses:
        '200':
          description: Successful
          schema:
            $ref: '#/definitions/Users'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ReturnCode'
        default:
          description: Unexpected recovery response
          schema:
            $ref: '#/definitions/ReturnCode'
  /xword:
    get:
      tags:
        - xword
      description: Get xword from app
      responses:
        '200':
          description: Successful
          schema:
            $ref: '#/definitions/Xword'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ReturnCode'
        default:
          description: Unexpected recovery response
          schema:
            $ref: '#/definitions/ReturnCode'
    post:
      tags:
        - xword
      description: Adds xword to mongodb
      parameters:
        - in: body
          name: xword
          description: list of words and definitions in puzzle
          required: true
          schema:
            $ref: '#/definitions/Xword'
      responses:
        '200':
          description: Post xword successful response
          schema:
            $ref: '#/definitions/ReturnCode'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ReturnCode'
        default:
          description: Post word unexpected error response
          schema:
            $ref: '#/definitions/ReturnCode'
  /xword/solve/puzzle:
    put:
      tags:
        - xword_solve
      security:
        - user: []
      description: Checks if user has solved the xword and updates there count
      parameters:
        - in: body
          name: xword
          description: puzzle definition
          required: true
          schema:
            $ref: '#/definitions/CheckXword'
      responses:
          '200':
            description: Check xword successful response
            schema:
              $ref: '#/definitions/ReturnCode'
          '500':
            description: Internal Server Error
            schema:
              $ref: '#/definitions/ReturnCode'
          default:
            description: Post word unexpected error response
            schema:
              $ref: '#/definitions/ReturnCode'

definitions:
  Word:
    type: object
    required:
      - word
      - definition
    properties:
      word:
        type: string
      wordLength:
        type: integer
      definition:
        type: string
  Words:
    type: array
    items:
      $ref: '#/definitions/Word'
  User:
    type: object
    required:
      - username
    properties:
      username:
        type: string
      puzzles:
        type: integer
      words:
        type: integer
  Users:
    type: array
    items:
      $ref: '#/definitions/User'
  CheckWord:
    type: object
    required:
      - word_id
      - input
      - idx
      - dir
    properties:
      word_id:
        type: integer
      idx:
        type: integer
      dir:
        type: integer
      input:
        type: string
  CheckXword:
    type: object
    properties:
      xword_id:
        type: integer
      words:
        type: array
        items:
          $ref: '#/definitions/CheckWord'
  XwordWord:
    type: object
    required:
      - word_id
      - idx
      - dir
    properties:
      word_id:
        type: integer
      word_len:
        type: integer
      definition:
        type: string 
      idx:
        type: integer
      dir:
        type: integer
  Xword:
    type: object
    required:
      - words
      - size
    properties:
      id:
        type: integer
      size:
        type: integer
      words:
        type: array
        items:
          $ref: '#/definitions/XwordWord'
  ReturnCode:
    type: object
    properties:
      code:
        type: integer
        readOnly: true
      message:
        type: string
        readOnly: true
