// Code generated by go-swagger; DO NOT EDIT.

package xword_solve

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"github.com/pshebel/xword/api/models"
)

// NewPutXwordSolvePuzzleParams creates a new PutXwordSolvePuzzleParams object
// no default values defined in spec.
func NewPutXwordSolvePuzzleParams() PutXwordSolvePuzzleParams {

	return PutXwordSolvePuzzleParams{}
}

// PutXwordSolvePuzzleParams contains all the bound params for the put xword solve puzzle operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutXwordSolvePuzzle
type PutXwordSolvePuzzleParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*puzzle definition
	  Required: true
	  In: body
	*/
	Xword *models.CheckXword
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPutXwordSolvePuzzleParams() beforehand.
func (o *PutXwordSolvePuzzleParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.CheckXword
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("xword", "body"))
			} else {
				res = append(res, errors.NewParseError("xword", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Xword = &body
			}
		}
	} else {
		res = append(res, errors.Required("xword", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
