// Code generated by go-swagger; DO NOT EDIT.

package xword_solve

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutXwordSolvePuzzleHandlerFunc turns a function with the right signature into a put xword solve puzzle handler
type PutXwordSolvePuzzleHandlerFunc func(PutXwordSolvePuzzleParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutXwordSolvePuzzleHandlerFunc) Handle(params PutXwordSolvePuzzleParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutXwordSolvePuzzleHandler interface for that can handle valid put xword solve puzzle params
type PutXwordSolvePuzzleHandler interface {
	Handle(PutXwordSolvePuzzleParams, interface{}) middleware.Responder
}

// NewPutXwordSolvePuzzle creates a new http.Handler for the put xword solve puzzle operation
func NewPutXwordSolvePuzzle(ctx *middleware.Context, handler PutXwordSolvePuzzleHandler) *PutXwordSolvePuzzle {
	return &PutXwordSolvePuzzle{Context: ctx, Handler: handler}
}

/*PutXwordSolvePuzzle swagger:route PUT /xword/solve/puzzle xword_solve putXwordSolvePuzzle

Checks if user has solved the xword and updates there count

*/
type PutXwordSolvePuzzle struct {
	Context *middleware.Context
	Handler PutXwordSolvePuzzleHandler
}

func (o *PutXwordSolvePuzzle) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutXwordSolvePuzzleParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
